FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ParkEase.ParkingLotService/ParkEase.ParkingLotService.csproj", "ParkEase.ParkingLotService/"]
RUN dotnet restore "ParkEase.ParkingLotService/ParkEase.ParkingLotService.csproj"
COPY . .
WORKDIR "/src/ParkEase.ParkingLotService"
RUN dotnet publish -c Release -o /app/out

FROM base AS final
WORKDIR /app
COPY --from=build /app/out .
ENV ASPNETCORE_URLS=http://0.0.0.0:10000
ENTRYPOINT ["dotnet", "ParkEase.ParkingLotService.dll"]